[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
(
    ^/pyproject.toml
    | migrations
    | .git
    | .pytest_cache
    | __pycache__
    | .venv
    | env
    | venv
)
'''

[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true