# Generated by Django 5.1.3 on 2024-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airdrops",
            options={"verbose_name": "Airdrop", "verbose_name_plural": "Airdrops"},
        ),
        migrations.AlterModelOptions(
            name="botmessages",
            options={"verbose_name": "Message to bot", "verbose_name_plural": "Messages to bot"},
        ),
        migrations.AlterModelOptions(
            name="mailings",
            options={"verbose_name": "Mailing", "verbose_name_plural": "Mailings"},
        ),
        migrations.AlterModelOptions(
            name="pointcoefficients",
            options={"verbose_name": "Coefficient", "verbose_name_plural": "Coefficients"},
        ),
        migrations.AlterField(
            model_name="airdrops",
            name="points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="botmessages",
            name="message",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="mailings",
            name="message",
            field=models.CharField(default="", max_length=3000),
        ),
        migrations.AlterField(
            model_name="users",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="language",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="referral_link",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
    ]
