# Generated by Django 4.2.6 on 2024-11-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_airdrops_options_alter_botmessages_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessages",
            name="message",
            field=models.CharField(default="", max_length=3000),
        ),
        migrations.AlterField(
            model_name="botmessages",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
