# Generated by Django 5.1.3 on 2024-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_addresses_blockchain_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailings",
            name="message",
            field=models.CharField(default="None", max_length=3000),
        ),
        migrations.AlterField(
            model_name="users",
            name="bio",
            field=models.CharField(blank=True, default="None", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="language",
            field=models.CharField(blank=True, default="None", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="referral_link",
            field=models.CharField(default="None", max_length=500),
        ),
    ]
