# Generated by Django 4.2.6 on 2024-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_users_user_id_alter_users_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="address",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
