# Generated by Django 4.2.6 on 2024-11-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_addresses_blockchain_alter_addresses_owner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airdrops",
            name="message",
            field=models.TextField(default="None", max_length=3000),
        ),
        migrations.AlterField(
            model_name="airdrops",
            name="users",
            field=models.ManyToManyField(related_name="airdrops", to="backend.users"),
        ),
        migrations.AlterField(
            model_name="mailings",
            name="users",
            field=models.ManyToManyField(related_name="mailings", to="backend.users"),
        ),
    ]
