# Generated by Django 5.1.3 on 2024-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotMessages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=200)),
                ("message", models.CharField(default="", max_length=3000)),
            ],
            options={
                "verbose_name": "Message to bot",
                "verbose_name_plural": "Messages to bot",
            },
        ),
    ]
