# Generated by Django 4.2.6 on 2024-11-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botmessages",
            options={"verbose_name": "Bot message", "verbose_name_plural": "Bot messages"},
        ),
    ]
